Add a basic sanity test
buildwarden/buildwarden pull request #14
Opened 2023-11-16 21:05 UTC by booniepepper

*Issue #, if available:*

*Description of changes:*

Adds a sanity test that can be used for local testing

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-16 23:27 UTC, lesiw commented on Makefile
> +	&& cd ..
`&& cd` is bad because it will only return if successful. Not sure how this works in Makefile, but in a shell script, it's better to `(cd && things_that_might_fail)`

2023-11-16 23:31 UTC, booniepepper commented on Makefile
> +	&& cd ..
Hmm maybe I can script this in `sh`? I think I don't need to become a Make expert

2023-11-17 00:16 UTC, booniepepper commented on Makefile
> +	&& cd ..
(Also, moving to `sh` means I can shellcheck, I have no idea if there's a comparable tool for `make`)

2023-11-17 00:43 UTC, lesiw commented on Makefile
> +	&& cd ..
Yeah, we could move all of this to a `./build.sh` type deal, which will probably be easier to maintain than pure `make`.

2023-11-17 19:40 UTC, booniepepper commented
Forgive some force-push spam, I'm going to try to figure out CI here too

2023-11-17 19:55 UTC, lesiw requested changes

2023-11-17 19:55 UTC, lesiw commented on build.sh
> +  cd "$projroot"
Instead of returning back to the project root, only run `cd` in a subshell. `(cd "$builddir" ...)`

That returns us back to the original directory once the subshell completes, successfully or not.

2023-11-17 19:55 UTC, lesiw commented on build.sh
> +  *--help*) >&2 echo "USAGE: $(basename "$0") [COMMAND...]"
This is one heckuva wildcard. Why not search for it, I.e. `for arg in "$@"`

2023-11-17 19:55 UTC, lesiw commented on build.sh
> +test() {
`test` is a shell builtin/reserved word

2023-11-17 19:56 UTC, booniepepper commented
```
$ ./build.sh fmt test
Building at /Users/justin.hill/workplace/buildwarden/build
+ docker network create --driver bridge --gateway 172.24.0.1 --internal --subnet 172.24.0.0/29 warden-xrsohu9m
acdf3fb3150b9380e4c4ccca28c5f4ba11d80c3ceda8ffe98186da1d3c597962
+ docker container run --detach --interactive --name warden-xrsohu9m --network warden-xrsohu9m --privileged --tty --workdir /work docker:dind cat
fd78286d0f5ee6436d785ec274cf40fd541f14ca217c275c87dfb90e08851572
^C⏎
```

```
$ ./build.sh --help
USAGE: build.sh [COMMAND...]
COMMANDS:
    build, fmt, lint, test, tidy
```

2023-11-17 19:59 UTC, booniepepper commented on build.sh
> +  *--help*) >&2 echo "USAGE: $(basename "$0") [COMMAND...]"
sure

2023-11-17 20:00 UTC, booniepepper commented on build.sh
> +test() {
Ah right...

2023-11-17 20:09 UTC, lesiw approved these changes
Approved, feel free to merge in whenever you're done messing with CI

2023-11-17 20:12 UTC, merged